---
- hosts: Servers
  tasks:
  - name: Install nginx on the server
    sudo: true
    apt: pkg=nginx state=installed update_cache=true
    notify:
      - Start nginx server
  handlers:
  - name: Start nginx server
    service: name=nginx state=started
